name: Jeopardy
version: 0.1
main: me.dyzzal.mfjeo.Jeopardy
api-version: 1.20
authors: [ ur mom lol ]
description: AAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

commands:
  createstand:
    description: Creates a contestant stand
    usage: /<command>
